version: "3.5"

services:

##47000 - db
  db:
    container_name: db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "47000:1433"
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
    networks:
      - wallet

##47101 - api
  ui:
    image: wallet/api
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: api
    ports:
      - '47101:5000'
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    networks:
      - wallet
    depends_on:
      - db
    restart: 
      on-failure

networks:
  wallet:
    name: wallet-network