version: "3.5"

services:

##46002 - sql-server-db
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "46002:1433"
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
    networks:
      - bukalemun

##46101 - ui
  ui:
    image: bukalemun/ui
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: ui
    ports:
      - '46101:5000'
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - TZ=Turkey
    networks:
      - bukalemun
    depends_on:
      - sql-server-db
    restart: 
      on-failure

networks:
  bukalemun:
    name: bukalemun-network